### ISSUE TITLE
Is it really necessary to run reevoocop on specs?

### ISSUE THREAD

**Issue by davidsevcik** [reevoo/reevoocop#12]
I would be more relaxed about spec code in old projects.

**Comment by lpil** [comment]
I feel that rubocop should be run on specs.

The only point of rubocop is to make code more readable, the interpreter doesn't care how it's formatted, it's purely for our benefit.

If it's code that we're going to be reading and working upon, we should be using rubocop on it.

**Comment by reneklacan** [comment]
I agree with David, I think there is more harm than good in running reevoocop on revieworld specs because you are forced to spend twice the time just to fix some shit we can live with.

**Comment by lpil** [comment]
That's the thought process that caused the mess that is revieworld.

If we spend time making something better that is a good thing. We need to refactor away all this tech debt, and unless we have a reason to do it right now it's just going to be put off forever.

**Comment by mikekr1** [comment]
Sorry @lpil, I also agree with @davidsevcik. 

In an ideal world you would be right, however:

Although getting rid of tech debt is a good thing, it cannot all be done in one go. We need to consider the amount of time overhead required to appease reevoocop vs the roadmap commitments we have. If it takes 20% more time to get rid of this tech debt per story, that means that we are going to be not delivering another 20% on top of an already seriously strained Q4.

I believe that the fact we have reevoocop running for code changes is a good first step. It will gradually (and within rational reason) get rid of some of the tech debt. Once we've got a majority of the files reevoocop happy then we can look at forcing it on tests.

Finally - "That's the thought process that caused the mess that is revieworld." That's not necessarily correct. The causes for what the state of RW is like today were: 
- generations of developers
- an app that has been built from pre Rails 1
- evolving best practices
- 8 years of code
- etc...

**Comment by reneklacan** [comment]
I would also say that it's different with RW as it we are planning to deprecate it in favour of microservices. I think it make sense to fix these things in time of extraction as there will be lot of refactoring.

Just imagine being on support, you edit few lines in few files, you want to ship it so you can continue but your CI is not passing because of hundreds of offenses.

**Comment by mikekr1** [comment]
That's exactly what happened to me when I added 4 characters to a file... A simple fix took a chunk of the next day to ship, and Ed has since been working on refactoring it for hours at night.

**Comment by lpil** [comment]
That want a spec that caused that problem, but yes, it is going to be a problem with how linting is currently applied to revieworld.

It seems that we are discussing here is not whether style should be enforced on specs, but how we manage style on legacy projects.

I think that on new projects we should treat specs the same way as production code. However I'm not sure that how we're enforcing it with legacy projects is the most suitable way to do it with our current situation.

**Comment by errm** [comment]
On the whole specs are much simpler to fix than code in classes.

`reevoocop -a` fixes 99% of the issues with revieworld specs.

The main issue that reevoocop brings up that it is hard to fix is things like method length, complexity class size these just don't apply to rspec specs as there are no classes or methods. If we still had test-unit stuff it would go wild . . . 

There is a discussion to be had on wether we want to slowly get revieworld, and other legacy applications to comply - or not, but don't think that excluding specs is a good idea, or saves us much effort.  The bit that takes the time is fixing the real code, and oftentimes in revieworld it requires some refactoring to get it to pass, because there are lots of big classes with large methods.
