### ISSUE TITLE
Style/DoubleNegation is stupid

### ISSUE THREAD

**Issue by errm** [reevoo/reevoocop#18]
Sometimes I/we do something like this

``` ruby
def foo?
  !!@foo
end
```

I see nothing harmful in this code, so I think we should disable the cop that moans about this.

**Comment by seddy** [comment]
I'm fine with this.  Only question I have: is there a different way of doing it that cop prefers, and if so why?

**Comment by lpil** [comment]
Why would you ever want to do this in a duck toured language?

**Comment by errm** [comment]
Lets say you were serialising stuff as json:

and you get this response

``` json
{
  "has_foos": ["james", "jimmy"]
}
```

but were totally expecting

``` json
{
  "has_foos": true
}
```

I would say it is understandable for caller of the `foo?` method to expect that `foo?` would not ever return a bunch of data . . .

Perhaps I am being neurotic though.

The style guide suggestion is:

``` ruby
def foo?
  !@foo.nil?
end
```

Which would work in this case, but can't just be used in place of existing code as `false.nil? #=> false`

**Comment by errm** [comment]
Oh and do duck toured languages have anything to do with these: https://en.wikipedia.org/wiki/Duck_tour

**Comment by seddy** [comment]
@lpil so that your return values are always truthy from predicate methods.  By using `!!`, you can do:

``` ruby
@foo = "bar"
foo? # => true
@foo = nil
foo? # => false
```

@errm - agree that `!!` may make more sense than `!@foo.nil?` because it covers the boolean case.

I suppose it depends on what your intention of the method is - if you're expecting a string for a particular attribute, you'd expect a predicate method of the same name to just return whether it's set or not, but if it's a boolean you'd expect it to just return the value.  `!!` seems to cover both cases, so I'm fine with disabling that reevoocop.

**Comment by mikekr1** [comment]
I'm in favor of using `!!`

**Comment by lpil** [comment]
Ah, yes. Public APIs. That's why I disabled this rule.

I think ruby should have `.to_bool`.
